# Generated by Django 3.2 on 2021-10-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='current_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='old_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='price_difference',
            field=models.FloatField(default=0),
        ),
    ]
