# Generated by Django 3.2 on 2021-10-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20211012_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='product_description',
            field=models.TextField(blank=True),
        ),
    ]
